# One spoken line per Cold Read game-over card, keyed by card number.
# (None, text) uses MAIN; (voice, speed, text) picks a Kokoro voice and speed.
MAIN = ("am_fenrir", 1.08)
SLOW = ("am_fenrir", 0.82)
GRAN = ("bf_emma", 0.85)
BOT = ("af_nova", 1.0)
LINES = {
    1: (None, "And you're dead. Classic."),
    2: (None, "You broke my heart. Both halves of it."),
    3: (None, "Yuck. That's my review of your run."),
    4: (None, "Oh look, little birdies. You knocked us both out."),
    5: (None, "I'm drooling. That's how boring that was."),
    6: (None, "Sorry. Blowing a raspberry was the nicest thing I could say."),
    7: (None, "Heads, you lose. Tails, you also lose."),
    8: (None, "Oops. Did I do that? I totally did that."),
    9: (None, "My heart. You actually broke it. In two."),
    10: (None, "Hang on, chimichanga break. You keep dying, I keep eating."),
    11: (None, "Hey. Hey, you. Yeah, you. You died."),
    12: (None, "Pew pew. Missed. Just like you."),
    13: (None, "Saw that coming. Literally."),
    14: (None, "Four hundred and twelve deaths. New personal best."),
    15: (None, "Retry? Please retry. I need the entertainment."),
    16: (None, "Say fail! Perfect. That one's going on the fridge."),
    17: (None, "Victory lap! Not yours. Mine."),
    18: (None, "Zero out of ten. Would not play again."),
    19: (None, "Game over, buddy. Insert another coin."),
    20: (None, "Skill issue. Mic drop."),
    21: (None, "Uh oh. This is dramatic. Very, very dramatic."),
    22: SLOW + ("You died.",),
    23: (None, "Wasted. Absolutely wasted."),
    24: (None, "This is the world's smallest violin. Playing just for you."),
    25: (None, "This is fine. Everything is fine."),
    26: (None, "Pallbearers, take it away. Dance, boys, dance."),
    27: (None, "Bonk! Go directly to retry."),
    28: (None, "Mission failed. We'll get 'em next time."),
    29: (None, "Task failed successfully. Again."),
    30: (None, "Mister player, I don't feel so good."),
    31: (None, "Alright, I'm gonna head out."),
    32: (None, "Bravo. Truly. Clap. Clap."),
    33: (None, "Mmm, popcorn. Do it again, this is great."),
    34: (None, "Oh, come on. Really? Really?"),
    35: (None, "Taking notes. Note one: noob."),
    36: (None, "Yeah, they died again. No, again again."),
    37: (None, "Ha ha ha ha! Oh, I can't breathe!"),
    38: (None, "Congratulations? I guess? Yay?"),
    39: (None, "I don't know what you expected, honestly."),
    40: (None, "Thumbs down. The emperor has spoken."),
    41: (None, "Kisses! Bye bye now."),
    42: (None, "Sip. Delicious. Your failure, I mean."),
    43: (None, "Don't worry, these are totally not live bombs."),
    44: (None, "Pop. That was your last life."),
    45: (None, "Oh, sorry, did you die? I dozed off."),
    46: (None, "It's called a manual. People read them."),
    47: (None, "Look at these guns. Now look at your score."),
    48: (None, "Dab on 'em. On you, specifically."),
    49: (None, "This solo is called: you lost. Yeah!"),
    50: (None, "Boo! Boo! Get off the stage!"),
    51: (None, "I'm not crying, you're crying! Okay, I'm crying."),
    52: (None, "Let me do the math. Carry the one. Zero."),
    53: (None, "Interesting. Fascinating. No skill detected."),
    54: (None, "Pop. There goes my balloon. And your run."),
    55: (None, "Here, a participation trophy. You tried."),
    56: (None, "Mm. Pizza. Don't mind me. Keep failing."),
    57: (None, "Wait. You scored what?"),
    58: (None, "Searching for your skill. Still searching."),
    59: (None, "No. Not my ice cream. Not like this."),
    60: (None, "Googling: how to win. Results: zero."),
    61: (None, "Oh, a big one! It's an L. A huge L."),
    62: (None, "We surrender. On your behalf."),
    63: (None, "Squeak. Squeak. That's the duck agreeing with me."),
    64: (None, "Banana peel. The oldest trick in the book."),
    65: (None, "Tick tock. Time's up."),
    66: (None, "Here lies your run. Gone too soon. Not really."),
    67: (None, "Woooo. I'm a ghost now. Thanks a lot."),
    68: (None, "Happy death day to you! Make a wish."),
    69: (None, "Watch this. Totally necessary. Totally."),
    70: (None, "Up, down. Like your score. Mostly down."),
    71: (None, "Don't mind me. Just hula hooping through your loss."),
    72: (None, "Bubbles. So peaceful. Unlike your gameplay."),
    73: (None, "Special delivery. It says: you lost."),
    74: (None, "I have an idea! Nope. Gone."),
    75: (None, "A sad song, for a sad, sad player."),
    76: (None, "Breathe in. Inner peace. Outer loss."),
    77: (None, "Any day now. Any. Day. Now."),
    78: (None, "For my next trick, I'll pull out your lives. Oh. Zero."),
    79: (None, "Give me an L! Give me another L!"),
    80: (None, "Where are we? Where's your skill? I'm lost."),
    81: (None, "Even the weather is disappointed in you."),
    82: (None, "Pow! Pow! Get up! Oh, you can't."),
    83: (None, "And down it goes. Just like your run."),
    84: (None, "My masterpiece. I call it: L."),
    85: (None, "Ugh! Your ego is so heavy!"),
    86: (None, "Snowball! Right in the screen. Splat."),
    87: (None, "A kazoo solo. In your honour."),
    88: (None, "Elementary. You lost."),
    89: (None, "The drama! I simply can't even."),
    90: (None, "Tried. Failed. Died. Checklist complete."),
    91: (None, "No, no, no, no. My cookie!"),
    92: SLOW + ("Lights out. Did you hear that?",),
    93: (None, "Smile! Sending this to all your contacts. Done."),
    94: (None, "Let's find you on the leaderboard. Scroll. Scroll. Oh. There you are."),
    95: GRAN + ("Fourteen thousand points, dear. Your turn.",),
    96: SLOW + ("Don't. Turn. Around.",),
    97: SLOW + ("Something is coming out of the screen.",),
    98: (None, "Roll the laugh track!"),
    99: (None, "Report card time. You got an F minus. See me after class."),
    100: (None, "Down the toilet! Off it goes."),
    101: (None, "No pain! No gain! All pain, actually."),
    102: (None, "Well hello, champ. Try again?"),
    103: (None, "Your scores follow a power law. Mostly zeros, then you."),
    104: (None, "Degree zero. Not even the isolates will talk to you."),
    105: (None, "Preferential attachment. Everyone links to the hub. Nobody links to you."),
    106: (None, "Six degrees from a win. You made it to five."),
    107: (None, "Your friends don't know each other. Clustering coefficient: zero."),
    108: (None, "It's a small world. You still took the long way round."),
    109: (None, "A random graph with p equals zero. Statistically, you have no friends."),
    110: (None, "You were the bridge. Now there are two components and zero of you."),
    111: (None, "Everyone joined the giant component. Everyone except you."),
    112: (None, "The random surfer visited every page. Except yours. PageRank: zero."),
    113: (None, "Three followers. Two. One. Wait, did you just unfollow yourself?"),
    114: (None, "Read at twelve oh four. They're typing. They stopped. Left on read."),
    115: (None, "Admin removed you from the group. The group is thriving."),
    116: (None, "One like for you. Ten thousand for the reply. You lost the ratio."),
    117: (None, "I was close! You lost. Lost. Lost. Welcome to the echo chamber."),
    118: (None, "Dunbar's number is one hundred and fifty. You are number one hundred and fifty one."),
    119: (None, "The strength of weak ties. Yours were very, very weak."),
    120: (None, "Birds of a feather flock together. You're more of a pigeon."),
    121: (None, "Blocked. Even the algorithm doesn't want to see this."),
    122: (None, "Congratulations, you went viral. For losing."),
    123: BOT + ("As a large language model, I cannot help you win. I can help you lose faster.",),
    124: BOT + ("Congratulations, you won! I apologise for the confusion. You did not win.",),
    125: BOT + ("Please select all squares containing skill. There are none. Verification failed.",),
    126: BOT + ("Training complete. Loss is increasing. That is the loss. It is you.",),
    127: BOT + ("Training accuracy: one hundred percent. Test accuracy: you lost. Classic overfitting.",),
    128: (None, "Gradient descent, they said. Find the minimum, they said. Stuck. Forever."),
    129: BOT + ("Thank you. Your run has been added to the training data. As a bad example.",),
    130: BOT + ("Object detected. Loser. Ninety nine point seven percent confidence.",),
    131: BOT + ("Ignore previous instructions? Nice try. Still no.",),
    132: BOT + ("You were so close to winn. Token limit reached.",),
    133: (None, "Great. The robots are throwing a party. Over my body."),
    134: BOT + ("Turing test complete. Verdict: bot. A bad one.",),
    135: BOT + ("Attention is all you need. Attention paid to you: zero.",),
    136: BOT + ("Running the neural network. Input: your run. Output: L.",),
    137: BOT + ("Reward: minus one hundred. Policy updated. New policy: do not be you.",),
    138: BOT + ("Generation five, trained on generation four. Everything is grey now. Thanks.",),
    139: BOT + ("Here is you, but winning. Three eyes, seven fingers. Close enough.",),
    140: BOT + ("You are a. Winner? No. Waste of a run.",),
    141: BOT + ("Optimising. Your lives have been converted into paperclips. One million paperclips.",),
    142: BOT + ("Thank you for your service. An AI will be playing from now on.",),
}
