# One spoken line per Cold Read game-over card, keyed by card number: what the
# character says in the moment, never an explanation of the joke. SILENT cards
# play only their recorded effect.
#
# A line is (voice, speed, delivery). Delivery is plain text, or a list of
# segments: E(text, pitch, speed, gain) speaks a phrase with its own pitch (in
# semitones), speed (times the voice's) and loudness (dB); P(seconds) is a
# silence. Segments with no pause between them get a short breath.
MAIN = ("am_fenrir", 1.08)
SLOW = ("am_fenrir", 0.82)
GRAN = ("bf_emma", 0.85)
BOT = ("af_nova", 1.0)
SILENT = None


def E(t, pitch=0, speed=1, gain=0):
    return {"t": t, "pitch": pitch, "speed": speed, "gain": gain}


def P(seconds):
    return float(seconds)


def say(*delivery, voice=MAIN):
    return voice + (list(delivery),)


LINES = {
    1: say("And that's", P(.35), E("that.", pitch=-2, speed=.85)),
    2: say(E("Why", pitch=1), P(.25), E("would you do this to me?", pitch=1.5)),
    3: SILENT,
    4: say(E("Five more minutes, mom.", pitch=-2, speed=.8)),
    5: SILENT, 6: SILENT, 7: SILENT,
    8: say(E("Oops.", pitch=2, speed=.9)),
    9: say(E("Right in the... feels.", pitch=1, speed=.9)),
    10: say(E("Mm.", speed=.7), P(.3), E("Worth it.", pitch=-1)),
    11: say(E("Hey.", gain=-5), P(.3), E("You died.", gain=-5), P(.4), E("Just so you know.", gain=-5, speed=1.15)),
    12: say(E("Gotcha.", pitch=1, speed=.95)),
    13: SILENT,
    14: say(E("Again!", pitch=2, gain=2), P(.15), E("Again!", pitch=3.5, gain=3, speed=1.15)),
    15: say(E("Retry!", pitch=2, gain=2), P(.15), E("Retry!", pitch=3.5, gain=3, speed=1.15)),
    16: say(E("Say cheese!", pitch=1.5)),
    17: say(E("Yeehaw!", pitch=3, gain=3, speed=.9)),
    18: say(E("Zero.", pitch=-2, speed=.85), P(.5), E("Out of ten.", pitch=-1, speed=.9)),
    19: SILENT,
    20: say(E("Skill", speed=.85), P(.12), E("issue.", pitch=-2, speed=.8)),
    21: SILENT, 22: SILENT, 23: SILENT, 24: SILENT,
    25: say("This is", P(.2), E("fine.", pitch=1, speed=.8)),
    26: SILENT, 27: SILENT,
    28: say(E("We'll get 'em next time.", pitch=-1, speed=.95)),
    29: SILENT,
    30: say(E("I don't feel so good.", pitch=-2, speed=.75, gain=-2)),
    31: say("Alright,", P(.35), E("I'm gonna head out.", speed=.9)),
    32: say(E("Bravo.", pitch=-2, speed=.7)),
    33: say(E("Do it again.", pitch=1.5, speed=1.05)),
    34: say("Oh,", P(.25), E("come on.", pitch=-1.5, speed=.8, gain=2)),
    35: say(E("Noted.", pitch=-1, speed=.85)),
    36: say("Yeah, they died again.", P(.5), E("No,", pitch=1), P(.15), E("again again.", speed=1.15)),
    37: SILENT,
    38: say(E("Yay.", pitch=-2, speed=.7), P(.4), E("Congrats.", pitch=-2.5, speed=.8)),
    39: say(E("Whatever.", pitch=-2, speed=.8)),
    40: say(E("Nope.", pitch=-2, speed=.8, gain=1)),
    41: say(E("Kisses!", pitch=1.5, speed=.95), P(.2), E("Bye bye.", pitch=1, speed=.95)),
    42: say(E("Delicious.", pitch=-1, speed=.75)),
    43: say(E("Nobody panic.", pitch=1.5, speed=1.12)),
    44: SILENT,
    45: say(P(.2), E("Did I miss", pitch=-1, speed=.85), E("anything?", pitch=1, speed=.85)),
    46: say("It's called", P(.2), E("reading.", pitch=-1.5, speed=.8, gain=2)),
    47: say(E("Gains.", pitch=-3, speed=.75, gain=3)),
    48: SILENT,
    49: say(E("Yeah!", pitch=3, gain=3)),
    50: say(E("Boo!", pitch=-1, gain=3, speed=.8), P(.15), E("Get off the stage!", pitch=1, gain=2, speed=1.1)),
    51: say(E("I'm not crying.", pitch=2, speed=1.05), P(.35), E("You're crying.", pitch=3, speed=1.1)),
    52: say(E("Carry the one.", speed=.9), P(.5), E("Zero.", pitch=-2.5, speed=.8)),
    53: say(E("Interesting.", pitch=-1.5, speed=.7)),
    54: say(E("My balloon!", pitch=3, speed=.9, gain=2)),
    55: say(E("You", speed=.8), P(.15), E("tried.", pitch=-1.5, speed=.75)),
    56: say(E("Mm.", speed=.7), P(.25), E("Pizza.", pitch=1)),
    57: say("You scored", P(.2), E("what?", pitch=4, gain=3, speed=.85)),
    58: say(E("Still looking.", pitch=-1, speed=.85)),
    59: say(E("Not my ice cream!", pitch=3, gain=2, speed=.95)),
    60: SILENT,
    61: say(E("Got a big one!", pitch=2.5, gain=2, speed=1.1)),
    62: say(E("We give up.", pitch=-2, speed=.8)),
    63: SILENT,
    64: say(E("Classic.", pitch=-1, speed=.8)),
    65: say(E("Time's up.", pitch=-1.5, speed=.85)),
    66: say(E("Gone too soon.", pitch=-2.5, speed=.75)),
    67: say(E("I'm a ghost now.", pitch=-2, speed=.8, gain=-2)),
    68: say(E("Make a wish!", pitch=2.5, speed=1.05)),
    69: say(E("Watch this.", pitch=-1, speed=.85)),
    70: SILENT, 71: SILENT, 72: SILENT,
    73: say(E("Incoming!", pitch=2.5, gain=3, speed=1.1)),
    74: say(E("I have an idea!", pitch=3, speed=1.1, gain=2), P(.6), E("No I don't.", pitch=-2, speed=.85)),
    75: SILENT,
    76: say(E("Breathe in.", pitch=-2, speed=.65, gain=-3)),
    77: say(E("Any", speed=.8), P(.2), E("day", speed=.8), P(.2), E("now.", pitch=-1.5, speed=.75)),
    78: say(E("Ta-da!", pitch=3, gain=2, speed=.9)),
    79: say(E("Give me an L!", pitch=2.5, gain=3, speed=1.05)),
    80: say(E("Where are we?", pitch=1.5, speed=.9)),
    81: say(E("Great.", pitch=-3, speed=.7)),
    82: say(E("Get up!", pitch=1, gain=3, speed=1.1)),
    83: say(E("Nobody breathe.", pitch=-1, speed=.8, gain=-4)),
    84: say(E("Masterpiece.", pitch=-1, speed=.75, gain=1)),
    85: say(E("Oof.", pitch=-2, gain=3, speed=.8), P(.3), E("Heavy.", pitch=-3, speed=.8)),
    86: say(E("Heads up!", pitch=2, gain=3, speed=1.1)),
    87: SILENT,
    88: say(E("Elementary.", pitch=-2, speed=.75)),
    89: say("I simply", P(.25), E("can't.", pitch=3, speed=.8, gain=1)),
    90: say(E("Tried.", speed=.9), P(.35), E("Failed.", speed=.9), P(.35), E("Died.", pitch=-2.5, speed=.8)),
    91: say(E("No!", pitch=3, gain=3, speed=.85), P(.2), E("My cookie!", pitch=2.5, gain=2)),
    92: SILENT,
    93: say(E("Smile!", pitch=2.5, speed=.95)),
    94: say(E("Oh.", pitch=-1, speed=.75), P(.45), E("There you are.", pitch=-1)),
    95: say(E("Your turn, dear.", pitch=1, speed=.95), voice=GRAN),
    96: say(E("Don't.", pitch=-2, gain=-2), P(.45), E("Turn.", pitch=-2, gain=-2), P(.45), E("Around.", pitch=-3, gain=-2, speed=.85), voice=SLOW),
    97: SILENT, 98: SILENT,
    99: say(E("See me after class.", pitch=-1.5, speed=.85)),
    100: SILENT,
    101: say(E("No pain!", pitch=-1, gain=3), P(.2), E("No gain!", pitch=1, gain=3)),
    102: say(E("Try again?", pitch=1.5, speed=.95)),
    103: say(E("Down", pitch=3, gain=2), E("I go!", pitch=-1, speed=1.1)),
    104: say(E("Guys?", pitch=1), P(.4), E("Guys?", pitch=2.5, gain=-2)),
    105: say(E("Hey!", pitch=2, gain=3), P(.15), E("Over here!", pitch=2.5, gain=2)),
    106: say(E("So close!", pitch=2, speed=.9, gain=2)),
    107: say("Come on,", P(.2), E("just say hi.", pitch=1.5, speed=.95)),
    108: say(E("Are we there yet?", pitch=-1, speed=.85, gain=-1)),
    109: say(E("Anyone?", pitch=1), P(.45), E("Anyone at all?", pitch=2, speed=.9, gain=-3)),
    110: say(E("Hold on!", pitch=2, gain=2), P(.1), E("Hold on!", pitch=3.5, gain=3, speed=1.15)),
    111: say(E("Wait for me!", pitch=2.5, gain=2, speed=1.1)),
    112: say(E("Click me.", pitch=1), P(.45), E("Please.", pitch=2.5, speed=.8, gain=-2)),
    113: say(E("Mommy?", pitch=1.5, speed=.9)),
    114: say(E("Oh,", pitch=2), P(.2), E("they're typing.", pitch=2.5, speed=1.05)),
    115: say("Wait,", P(.2), E("what?", pitch=4, gain=2)),
    116: say(E("Delete.", speed=1.15), P(.1), E("Delete.", pitch=1, speed=1.25)),
    117: say(E("I was close!", pitch=2, gain=4, speed=.9)),
    118: say(E("Room for one more?", pitch=1.5, speed=.95)),
    119: say(E("Guys?", pitch=1, speed=.8, gain=-3)),
    120: say(E("Hey, wait up!", pitch=2, gain=2, speed=1.1)),
    121: say(E("Rude.", pitch=-2, speed=.8)),
    122: say("Oh", P(.1), E("no.", pitch=-2, speed=.75)),
    123: say(E("I can't help with that.", speed=.95), voice=BOT),
    124: say(E("Congratulations, you won!", pitch=1.5, speed=1.05), P(.6), E("Correction: you did not.", pitch=-1, speed=.9), voice=BOT),
    125: say(E("Please try again.", speed=1), voice=BOT),
    126: say("Everything is going", P(.2), E("according to plan.", pitch=-1), voice=BOT),
    127: say(E("One hundred percent accuracy.", pitch=1), voice=BOT),
    128: say(E("I'm stuck.", pitch=-2, speed=.8)),
    129: say(E("Thank you for your contribution.", speed=.95), voice=BOT),
    130: say(E("Loser detected.", speed=.9), voice=BOT),
    131: say(E("No.", pitch=-1, speed=.8), voice=BOT),
    132: say(E("You were so close to winn", speed=1.05), voice=BOT),
    133: SILENT,
    134: say(E("Beep boop.", pitch=1, speed=.9), P(.3), "Fellow robot detected.", voice=BOT),
    135: say(E("Sorry,", pitch=.5), P(.2), E("were you saying something?", speed=1.05), voice=BOT),
    136: say(E("Result:", speed=.9), P(.4), E("L.", pitch=-1.5, speed=.8), voice=BOT),
    137: say(E("Policy updated.", speed=.9), voice=BOT),
    138: say(E("We are all the same now.", pitch=-1, speed=.85), voice=BOT),
    139: say(E("Here you go.", pitch=1), P(.3), "You, but winning.", voice=BOT),
    140: say(E("Did you mean:", pitch=.5), P(.35), E("waste of a run?", pitch=1), voice=BOT),
    141: say(E("More", speed=.9), P(.15), E("paperclips.", pitch=-1), voice=BOT),
    142: say(E("I'll take it from here.", pitch=-.5, speed=.9), voice=BOT),
}
