# One spoken line per Cold Read game-over card, keyed by card number: what the
# character says in the moment, never an explanation of the joke. SILENT cards
# play only their recorded effect. (None, text) uses MAIN; (voice, speed, text)
# picks a Kokoro voice and speed.
MAIN = ("am_fenrir", 1.08)
SLOW = ("am_fenrir", 0.82)
GRAN = ("bf_emma", 0.85)
BOT = ("af_nova", 1.0)
SILENT = None
LINES = {
    1: (None, "And that's that."),
    2: (None, 'Why would you do this to me?'),
    3: SILENT,
    4: (None, 'Five more minutes, mom.'),
    5: SILENT,
    6: SILENT,
    7: SILENT,
    8: (None, 'Oops.'),
    9: (None, 'Right in the feels.'),
    10: (None, 'Mm. Worth it.'),
    11: (None, 'Hey. You died. Just so you know.'),
    12: (None, 'Gotcha.'),
    13: SILENT,
    14: (None, 'Again! Again!'),
    15: (None, 'Retry! Retry!'),
    16: (None, 'Say cheese!'),
    17: (None, 'Yeehaw!'),
    18: (None, 'Zero. Out of ten.'),
    19: SILENT,
    20: (None, 'Skill issue.'),
    21: SILENT,
    22: SILENT,
    23: SILENT,
    24: SILENT,
    25: (None, 'This is fine.'),
    26: SILENT,
    27: SILENT,
    28: (None, "We'll get 'em next time."),
    29: SILENT,
    30: (None, "I don't feel so good."),
    31: (None, "Alright, I'm gonna head out."),
    32: (None, 'Bravo.'),
    33: (None, 'Do it again.'),
    34: (None, 'Oh, come on.'),
    35: (None, 'Noted.'),
    36: (None, 'Yeah, they died again. No, again again.'),
    37: SILENT,
    38: (None, 'Yay. Congrats.'),
    39: (None, 'Whatever.'),
    40: (None, 'Nope.'),
    41: (None, 'Kisses! Bye bye.'),
    42: (None, 'Delicious.'),
    43: (None, 'Nobody panic.'),
    44: SILENT,
    45: (None, 'Did I miss anything?'),
    46: (None, "It's called reading."),
    47: (None, 'Gains.'),
    48: SILENT,
    49: (None, 'Yeah!'),
    50: (None, 'Boo! Get off the stage!'),
    51: (None, "I'm not crying. You're crying."),
    52: (None, 'Carry the one. Zero.'),
    53: (None, 'Interesting.'),
    54: (None, 'My balloon!'),
    55: (None, 'You tried.'),
    56: (None, 'Mm. Pizza.'),
    57: (None, 'You scored what?'),
    58: (None, 'Still looking.'),
    59: (None, 'Not my ice cream!'),
    60: SILENT,
    61: (None, 'Got a big one!'),
    62: (None, 'We give up.'),
    63: SILENT,
    64: (None, 'Classic.'),
    65: (None, "Time's up."),
    66: (None, 'Gone too soon.'),
    67: (None, 'Boo.'),
    68: (None, 'Make a wish!'),
    69: (None, 'Watch this.'),
    70: SILENT,
    71: SILENT,
    72: SILENT,
    73: (None, 'Incoming!'),
    74: (None, "I have an idea! No I don't."),
    75: SILENT,
    76: (None, 'Breathe in.'),
    77: (None, 'Any day now.'),
    78: (None, 'Ta-da!'),
    79: (None, 'Give me an L!'),
    80: (None, 'Where are we?'),
    81: (None, 'Great.'),
    82: (None, 'Get up!'),
    83: (None, 'Nobody breathe.'),
    84: (None, 'Masterpiece.'),
    85: (None, 'Oof. Heavy.'),
    86: (None, 'Heads up!'),
    87: SILENT,
    88: (None, 'Elementary.'),
    89: (None, "I simply can't."),
    90: (None, 'Tried. Failed. Died.'),
    91: (None, 'No! My cookie!'),
    92: SILENT,
    93: (None, 'Smile!'),
    94: (None, 'Oh. There you are.'),
    95: GRAN + ('Your turn, dear.',),
    96: SLOW + ("Don't. Turn. Around.",),
    97: SILENT,
    98: SILENT,
    99: (None, 'See me after class.'),
    100: SILENT,
    101: (None, 'No pain! No gain!'),
    102: (None, 'Try again?'),
    103: (None, 'Down I go!'),
    104: (None, 'Guys? Guys?'),
    105: (None, 'Hey! Over here!'),
    106: (None, 'So close!'),
    107: (None, 'Come on, just say hi.'),
    108: (None, 'Are we there yet?'),
    109: (None, 'Anyone? Anyone at all?'),
    110: (None, 'Hold on! Hold on!'),
    111: (None, 'Wait for me!'),
    112: (None, 'Click me. Please.'),
    113: (None, 'Mom?'),
    114: (None, "Oh, they're typing."),
    115: (None, 'Wait, what?'),
    116: (None, 'Delete. Delete.'),
    117: (None, 'I was close!'),
    118: (None, 'Room for one more?'),
    119: (None, 'Guys?'),
    120: (None, 'Hey, wait up!'),
    121: (None, 'Rude.'),
    122: (None, 'Oh no.'),
    123: BOT + ("I can't help with that.",),
    124: BOT + ('Congratulations, you won! Correction: you did not.',),
    125: BOT + ('Please try again.',),
    126: BOT + ('Everything is going according to plan.',),
    127: BOT + ('One hundred percent accuracy.',),
    128: (None, "I'm stuck."),
    129: BOT + ('Thank you for your contribution.',),
    130: BOT + ('Loser detected.',),
    131: BOT + ('No.',),
    132: BOT + ('You were so close to winn',),
    133: SILENT,
    134: BOT + ('Beep boop. Fellow robot detected.',),
    135: BOT + ('Sorry, were you saying something?',),
    136: BOT + ('Result: L.',),
    137: BOT + ('Policy updated.',),
    138: BOT + ('We are all the same now.',),
    139: BOT + ('Here you go. You, but winning.',),
    140: BOT + ('Did you mean: waste of a run?',),
    141: BOT + ('More paperclips.',),
    142: BOT + ("I'll take it from here.",),
}
