import { chromium } from "playwright";
import { join } from "node:path";
import { launch, serve, ROOT } from "./lib.mjs";
import { openPage, settle } from "./engine.mjs";
const [out, url] = process.argv.slice(2);
const srv = await serve(out);
const browser = await launch(chromium);
const { page, state } = await openPage(browser, {});
state.origin = new URL(srv.base).origin;
await page.goto(srv.base + url, { waitUntil: "load" });
await settle(page, state);
await page.addScriptTag({ path: join(ROOT, "scripts/audit_week03.js") });
const r = await page.evaluate(async () => { try { return await window.auditWeek03({ verbose: false }); } catch (e) { return { err: e.message, stack: e.stack }; } });
console.log(JSON.stringify(r, null, 1).slice(0, 4000));
await browser.close(); srv.close();
